segment_lenth: [50,100,250,500] 
number_of_segs: [1000]

number_of_species: 5
pams: [10, 30, 50, 70, 90, 110, 130]
repeats: [1,2,3,4,5,6,7,8,9,10]

alf_dir: alf
scripts_dir: ../scripts/simulation

imp_dir: IMP
# imp_min_seg_length is not needed, use segment_lenth above.
imp_min_identity: [80]  # default: 80
imp_max_gap: [20]       # default: 13
imp_min_aln_len: [13]   # default: 13
imp_bucket_size: [1000] # default: 1000
